### ISSUE TITLE
TNT + Chest = Crash

### ISSUE THREAD

**Issue by BostinTeaParty** [CyclopsMC/ColossalChests#135]
#### Issue type:

- :bug: Bug
Crash
____

#### Short description:
Blowing up a colossal chest crashes the game 

#### Steps to reproduce the problem:

1. ...Obtain colossal chest
2. ...Ignite tnt next to chest

#### Expected behaviour:
Game crash

Game crash
____

#### Versions:
1.15.2

_**- This mod:**_ 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting, but could you share your crashlog please?

**Comment by facetorched** [comment]
Not sure if this helps, especially since I'm on 1.14.4 but here's my crash log. I think a creeper blew up my colossal chest.

https://pastebin.com/jxFpt7LU

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/jxFpt7LU">---- Minecraft Crash Report ----  // Uh... Did I do that?    Time: 5/18/20 1:54  - Pastebin.com</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Thanks!
