### ISSUE TITLE
lost all items when tried to attach interface

### ISSUE THREAD

**Issue by DimakSerpg** [CyclopsMC/ColossalChests#151]
for five years you couldn't make it to work properly? what a joke. are you seriously? just madness. it's like i decided to keep my money in the bank, and they just lost them lol

i'm newbie in minecraft, decided to play single play with rad modpack. and now just lost all items after hours of playing because of some bugged mod.. -___-

**Comment by rubensworks** [comment]
I understand you're annoyed, but being rude to the developer that offers a mod to you at zero cost is not appreciated.
As you can see in the open list of issues, there are no known bugs, so what you are talking about is a first.
The least you could do is create a proper bug report, or even better: open a pull request to fix the bug yourself.

Reactions like this are the reason many modders stop doing what they're doing, you know.
I hope you think twice before you speak like this in the future.

**Comment by DimakSerpg** [comment]
> Reactions like this are the reason many modders stop doing what they're doing, you know.
> I hope you think twice before you speak like this in the future.

I googled this problem, and you know what? This problem goes from 2017... that's why i'm surprised, for five years dev didn't fixed this. I have zero knowledge in programming, but I don't think that to make a box throw away items, not just DELETE THEM, it's some kind of problem.

**Comment by rubensworks** [comment]
> I have zero knowledge in programming

That is clear.
So don't complain about things you don't understand (such as regressions), that is –also– really rude.

I would also suggest improving your knowledge of English grammar, as I have a hard time understanding your sentences.

And again, if you really want a fix, open a bug report, or learn to program and fix the bug yourself, instead of throwing your annoyance at me.

**Comment by seriousfreezing** [comment]
Sorry to get into this discussion, but I had experienced this same situation years ago! I will never use this mod again - unless it has bugfix - I don't know why I switched from Refined Storage to Colossal Chests! I suffered with this same kind of bug, but at the time I didn't report it because I didn't remember nor wanted to do it at the time, I just gave up my map because of the loss of more than 1 million items.

I think it is disrespectful to ask about the client's knowledge of English! I know the programming world well and I recognize that it's not nice to tell your final client to bugfix his own project, even if he is not a programmer/developer, I understand that it's "open-source". 

"So don't complain about things you don't understand"

totally WRONG! The CLIENT ALWAYS HAS A RIGHT, no matter what you are talking about! If you made the mod free, you have to understand the consequences that there will always be bugs and there will always be criticism or bug reports! But it is disrespectful to ask your own customer not to complain about something they don't understand! This is one more reason not to go back on my decision not to use this mod of yours to go back to losing my items and having a headache!

Hope you found a better mod!

**Comment by rubensworks** [comment]
> totally WRONG! The CLIENT ALWAYS HAS A RIGHT, no matter what you are talking about!

I think you're confusing this free and open-source mod with a service you are paying for.

-----

In any case, locking this conversation before it becomes a ranting place.

For anyone else finding this issue; if you have a bug, please report it, and it will be fixed. If bugs are not reported, developers will probably not be aware of them, so fixing them is impossible them.
