### ISSUE TITLE
[1.18.2] User broke colossal chest, server crashed, now in a crash loop.

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/ColossalChests#155]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Someone broke their Colossal Chest, server froze, crashed and now won't start again. (In a crash loop.)

#### Steps to reproduce the problem:
Not entirely sure tbh, they broke a colossal chest (they said).
Then server froze, crashed due to watchdog. (which is set to 720000).
..

#### Expected behaviour:

That the it doesn't crash.

____

#### Versions:

- This mod: 1.8.3
- Minecraft: 1.18.2
- Forge: 40.1.48

#### Log file:

https://gist.github.com/Gbergz/d82a1a3aff71f20197e149b4c7b1d4f9

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Not sure how, but I think something horrible happened than breaking a colossal chest.
It looks like your chunk got horribly corrupted somehow, and MC is deadlocking when trying to load it.
No idea how such a thing could be achieved even.
Perhaps some other mod in your pack is messing with chunks and somehow broke it?

In any case, since Colossal Chests is just trying to load a tile entity here in this stacktrace, and MC is going in a deadlock during this, there's not much I can change on my end to fix this unfortunately.

I would recommend reverting to a backup. (and if possible, determining exactly what caused this problem)
Happy to re-open this if there's a reproducible setup with just Colossal Chests that can show the problem is caused by this mod.
