### ISSUE TITLE
Items can't be placed inside the chests in SMP

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/ColossalChests#17]
Apparently I didn't test this?

**Comment by rubensworks** [comment]
See https://github.com/CyclopsMC/CyclopsCore/issues/9

**Comment by Blue64** [comment]
Aren't they supposed to be piped in? ~~I noticed it had no GUI.~~

**Comment by rubensworks** [comment]
They do have a gui, if not, then that is a bug...
They can be piped in as well.

**Comment by Blue64** [comment]
~~Ah lol yea, it had no GUI,~~ I was like "how do I put the helmet in?" `XD` By The Way does it need identical items to get the boost, or is it just the same `ModID:Name`? Because if I recall, you are fixing the Damage, and the `{Meta}` parts shouldn't be needing comparison either right? (Just don't delete it's extra Meta lol TiCon uses that info lol)

P. S. I meant that the Collasal `(Blood)` Chest had no GUI.

Edit: strike throughs & corrections.

**Comment by Blue64** [comment]
P. S. I meant that the Collasal Chest had no GUI.

**Comment by rubensworks** [comment]
You know this is the Colossal Chests issue tracker right? ;) You are refering to the Colossal Blood Chest (which should have a gui as well btw...)

**Comment by Blue64** [comment]
Ah, I just noticed that, my bad lol but yeah, I couldn't get the Collasal Blood Chest to open for me at all. When I launch MC again I'll double check everything.

**Comment by rubensworks** [comment]
Fixed in CyclopsMC/CyclopsCore@47b6cb350cfdbd7703e5ab6e2a1958689a1d9d6d
