### ISSUE TITLE
Transferring between chests is CPU expensive

### ISSUE THREAD

**Issue by ouroborus** [CyclopsMC/ColossalChests#96]
I have a particularly beefy server (see [this reddit post](https://www.reddit.com/r/allthemods/comments/755bsq/cant_keep_up_server_performance_part_2/) for specs) and the minecraft server running on it uses hardly any CPU (typically about 12%). 

I'm attempting to transfer inventory from a 16^3 wooden chest to a 16^3 diamond chest. CPU for the core the server is running on is now pegged at 100% and "Can't keep up!" messages are giving skip times up to 80,000ms (1600 ticks).

**Comment by rubensworks** [comment]
Yes, this can be expensive. This is simply due to these chests having a huge amount of slots, not really much that can be done about that.

It however mainly depends on the type of item transfer mod you are using.
Integrated Tunnels for instance works really well with this mod, so you should see better performance with this. Furthermore, you can tweak the tick rate with this.

Note that this mod has an upgrade/downgrade tool that allows you to change the material type of your chest easily.

**Comment by ouroborus** [comment]
The upgrade/downgrade tool doesn't permit relocation.

It seem like other mods handle large inventory transfers without this issue being anywhere near this bad.

I think, at minimum, it might be useful to set the default maximum chest size to something more reasonable if performance will remain anywhere near the current level for the foreseeable future (assuming that chest size has a significant impact on this).

**Comment by rubensworks** [comment]
Sorry, nothing much I can do about this.

As most things in MC are slot-based, and this mod has a huge amount of slots, this results in a high computational complexity when you want to transfer _all_ items at the same time.

**Comment by AAA55688** [comment]
Cannot be used on the server
