### ISSUE TITLE
crash when using "+" of jei in tinker's craft station

### ISSUE THREAD

**Issue by zzyasia** [CyclopsMC/ColossalChests#99]
crash when using "+" of jei in tinker's craft station if the colossalchest is put near to it.It's not always happen.And no crash report,by the way.

**Comment by rubensworks** [comment]
Crashes always produce a crash report, otherwise it's not a crash.

So what exactly happens in your case?

**Comment by RealMangorage** [comment]
I had this issue and have a Log
for 1.16.5

https://pastebin.com/mHkFwPh6

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/mHkFwPh6">---- Minecraft Crash Report ----// My bad.Time: 7/28/23 10:03 AMDescript - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>
